# .github/workflows/deploy.yml
name: Deploy Frontend & Backend to ECS Fargate

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      ECR_REGISTRY:          ${{ secrets.ECR_REGISTRY }}
      CLUSTER_NAME:          ${{ secrets.CLUSTER_NAME }}
      FRONTEND_REPO:         ${{ secrets.FRONTEND_REPO }}
      BACKEND_REPO:          ${{ secrets.BACKEND_REPO }}
      FRONTEND_SERVICE:      ${{ secrets.FRONTEND_SERVICE_NAME }}
      BACKEND_SERVICE:       ${{ secrets.BACKEND_SERVICE_NAME }}
      FRONTEND_SUBNET_IDS:   ${{ secrets.FRONTEND_SUBNET_IDS }}
      BACKEND_SUBNET_IDS:    ${{ secrets.BACKEND_SUBNET_IDS }}
      FRONTEND_SG_IDS:       ${{ secrets.FRONTEND_SECURITY_GROUP_IDS }}
      BACKEND_SG_IDS:        ${{ secrets.BACKEND_SECURITY_GROUP_IDS }}

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # … (render & register steps unchanged) …

      - name: Create or update frontend service
        run: |
          if aws ecs describe-services \
               --cluster "$CLUSTER_NAME" \
               --services "$FRONTEND_SERVICE" \
               --query 'services[0].status' --output text \
               | grep -q "ACTIVE"; then
            aws ecs update-service \
              --cluster "$CLUSTER_NAME" \
              --service "$FRONTEND_SERVICE" \
              --task-definition "$FRONT_TASK_DEF_ARN" \
              --force-new-deployment
          else
            aws ecs create-service \
              --cluster "$CLUSTER_NAME" \
              --service-name "$FRONTEND_SERVICE" \
              --task-definition "$FRONT_TASK_DEF_ARN" \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[${FRONTEND_SUBNET_IDS}],securityGroups=[${FRONTEND_SG_IDS}],assignPublicIp=ENABLED}"
          fi

      - name: Create or update backend service
        run: |
          if aws ecs describe-services \
               --cluster "$CLUSTER_NAME" \
               --services "$BACKEND_SERVICE" \
               --query 'services[0].status' --output text \
               | grep -q "ACTIVE"; then
            aws ecs update-service \
              --cluster "$CLUSTER_NAME" \
              --service "$BACKEND_SERVICE" \
              --task-definition "$BACK_TASK_DEF_ARN" \
              --force-new-deployment
          else
            aws ecs create-service \
              --cluster "$CLUSTER_NAME" \
              --service-name "$BACKEND_SERVICE" \
              --task-definition "$BACK_TASK_DEF_ARN" \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[${BACKEND_SUBNET_IDS}],securityGroups=[${BACKEND_SG_IDS}],assignPublicIp=DISABLED}"
          fi
